#!/usr/bin/env node
// Extract an API signature reference from the Affinity SDK JSLib.
// Deterministic: every exported class + public method/static/getter/setter,
// plus exported top-level functions and re-exported enum names.
// Relies on the SDK's consistent formatting (col-0 classes/functions,
// one-indent members). Usage: node extract-api.js <JSLib-dir> > out.md
'use strict';
const fs = require('fs');
const path = require('path');

const dir = process.argv[2];
if (!dir || !fs.existsSync(dir)) { console.error('usage: extract-api.js <JSLib-dir>'); process.exit(1); }

const KEYWORDS = new Set(['if','for','while','switch','catch','return','function','else','do','typeof','new','class','const','let','var','throw','await','case']);

// member: <indent 1 level>(static)?(get|set|async)? name(params) {
const MEMBER = /^(\t| {2,8})(static\s+)?(get\s+|set\s+|async\s+)?([A-Za-z_$][\w$]*)\s*\(([^)]*)\)\s*\{/;
const CLASS  = /^class\s+([A-Za-z_$][\w$]*)\s*(?:extends\s+([\w$.]+)\s*)?\{?/;
const FUNC   = /^function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)/;
const EXPORT = /^module\.exports\.([A-Za-z_$][\w$]*)\s*=/;
// destructured native imports: const { A, B } = require('affinity:...')
const NATIVE = /=\s*require\(['"]affinity:[^'"]+['"]\)/;

function fileBase(f) { return f.replace(/\.js$/, ''); }

const files = fs.readdirSync(dir).filter(f => f.endsWith('.js')).sort();
const out = [];

out.push('# Affinity SDK — API Signature Reference (auto-generated)');
out.push('');
out.push('Regenerated by `extract-api.js` from the local JSLib copy. Every exported class +');
out.push('public member signature, grouped by file. `require(\'/<file>\')` to import.');
out.push('Enum **values** are native — read at runtime via `Enum.keys/.values/.entries`.');
out.push('Curated purpose notes (from the agent build) are NOT reproduced here.');
out.push('');
out.push('---');
out.push('');

for (const file of files) {
  const src = fs.readFileSync(path.join(dir, file), 'utf8');
  const lines = src.split('\n');

  const exportsList = [];
  const nativeEnums = [];
  const funcs = [];
  const classes = []; // {name, base, members:[]}

  // collect native enum import names (heuristic: imports from affinity:* that are also exported)
  for (const ln of lines) {
    if (NATIVE.test(ln)) {
      const m = ln.match(/\{([^}]*)\}/);
      if (m) m[1].split(',').forEach(s => { const n = s.trim(); if (n) nativeEnums.push(n); });
    }
    const ex = ln.match(EXPORT); if (ex) exportsList.push(ex[1]);
  }

  let cur = null;     // current class
  let depth = 0;      // brace depth, tracked only to find class end at depth 0
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (!cur) {
      const cm = raw.match(CLASS);
      if (cm && /^class\s/.test(raw)) {
        cur = { name: cm[1], base: cm[2] || null, members: [] };
        classes.push(cur);
        depth = (raw.match(/\{/g) || []).length - (raw.match(/\}/g) || []).length;
        continue;
      }
      const fm = raw.match(FUNC);
      if (fm) funcs.push(`${fm[1]}(${fm[2].trim()})`);
      continue;
    }
    // inside a class: detect members before updating depth so signature line counts as body-level
    const mm = raw.match(MEMBER);
    if (mm && depth === 1) {
      const name = mm[4];
      if (!KEYWORDS.has(name) && name !== 'constructor') {
        const stat = mm[2] ? 'static ' : '';
        const acc  = mm[3] ? mm[3].trim() + ' ' : '';
        const params = mm[5].trim();
        cur.members.push(`${stat}${acc}${name}(${params})`);
      }
    }
    depth += (raw.match(/\{/g) || []).length - (raw.match(/\}/g) || []).length;
    if (depth <= 0) cur = null;
  }

  // only emit files that expose something public
  if (!exportsList.length && !classes.length && !funcs.length) continue;

  out.push(`## ${file} — \`require('/${fileBase(file)}')\``);
  if (exportsList.length) out.push(`Exports: ${[...new Set(exportsList)].join(', ')}`);
  out.push('');
  for (const c of classes) {
    out.push(`### ${c.name}${c.base ? ' extends ' + c.base : ''}`);
    if (c.members.length) for (const m of c.members) out.push(`- \`${m}\``);
    else out.push('- (no public members)');
    out.push('');
  }
  if (funcs.length) { out.push(`Functions: ${funcs.map(f => '`' + f + '`').join(', ')}`); out.push(''); }
  // enums that are also exported (so they're real public enums of this module)
  const realEnums = [...new Set(nativeEnums)].filter(e => exportsList.includes(e));
  if (realEnums.length) { out.push(`Enums (native): ${realEnums.join(', ')} — values via .keys/.values/.entries`); out.push(''); }
}

process.stdout.write(out.join('\n'));
